### ISSUE TITLE
.Nav is element is not present in html

### ISSUE THREAD

**Issue by ullaskunder3** [v500nm/CAP-website#49]
Just out of curiosity, why did you do this ?
https://github.com/V500nm/CAP-website/blob/9900be4f884db33fdca90ada2a0dfd1c1e04ccd6/script.js#L59

causes:
```
Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at script.js:59:42
```

same goes to `.Footer`

**Comment by V500nm** [comment]
check the elements in header and footer tag classes 
the object functions are not for index page, it is for child pages

**Comment by ullaskunder3** [comment]
then why it is show like this => still
![image](https://user-images.githubusercontent.com/66258652/187273282-43cc6d3c-7e76-4e44-9e68-75042ca03193.png)

**Comment by V500nm** [comment]
does it showing any issue showing navbar and footer??
